### PR TITLE
Don't patch Ember Data unless file export is needed

### PR DESCRIPTION
**Pull request by mwpastore**
#367 (temporary workaround for those of us who don't need file export)

### CODE REVIEW

**Comment by marcemira** [comment]
Having the same issue, thanks for the fix @mwpastore, using your branch until this gets merged 👍🏻

**Comment by fsmanuel** [comment]
@mwpastore thanks for the PR! Do we know which version removed `Store.reopen`? To make the tests pass for `ember-release` we need to drop the initializer for all ember data versions > the version `Store.reopen` got removed.

**Comment by seanCodes** [comment]
@mwpastore Bump here. It would be awesome to get this merged.

**Comment by fsmanuel** [comment]
@mwpastore thanks for the PR. I ended up deprecating the intializer.

@marcemira @seanCodes [released as `v.2.0.5`](https://github.com/funkensturm/ember-local-storage/releases/tag/v2.0.5)

**Comment by seanCodes** [comment]
@fsmanuel Thank you!

**Pull request merged**
