### PR TITLE
Namespace storage based on type key

### PR DESCRIPTION
**Pull request by offirgolan**
This PR adds support for multiple storage type for a given model.

```js
{
  fooStorage: storageFor('foo', 'model'),
  barStorage: storageFor('bar', 'model')
}
```

### CODE REVIEW

**Comment by offirgolan** [comment]
Also build is failing because of SASS issue. Unrelated to this PR.

**Comment by fsmanuel** [comment]
@offirgolan thanks! I'll do a review soon.

**Comment by fsmanuel** [comment]
@offirgolan good catch!

**Comment by fsmanuel** [comment]
@offirgolan released as `1.4.0`

**Comment by offirgolan** [comment]
@fsmanuel glad to help. Thanks for the release! 😄

**Pull request merged**
