### PR TITLE
bugfix on queryFilter when filtering relationships with queryRecord  

### PR DESCRIPTION
**Pull request by bncoelho**
bugfix: queryFilter was incorrectly setting recordValue to null and later comparing it to undefined which caused queryRecord to fail when filtering by relationships.

Added tests to queryRecord.

### CODE REVIEW

**Comment by fsmanuel** [comment]
@bncoelho thanks! Will review in the next days.

**Comment by fsmanuel** [comment]
@bncoelho Amazing work!

**Comment by fsmanuel** [comment]
I'll let you know when the new release is out.

**Comment by bncoelho** [comment]
Thanks! My pleasure.

**Comment by fsmanuel** [comment]
`1.3.3` is released

**Comment by bncoelho** [comment]
Cool, thank you very much.

**Pull request merged**
