### PR TITLE
enhancement: Make _resetStorages public to allow people to use it to test their apps

### PR DESCRIPTION
**Pull request by dmuneras**
## Description 

Make `_resetStorages` public to provide a good way to clear the storage while testing the application.

I added a new section in the README to make it easier to find out that this helper is available.

### CODE REVIEW

**Comment by fsmanuel** [comment]
@dmuneras That looks great. Can you rebase to make the tests work?

**Comment by dmuneras** [comment]
@fsmanuel  done.

**Comment by fsmanuel** [comment]
@dmuneras I published `1.5.0`. Thanks again!

**Comment by dmuneras** [comment]
No problem @fsmanuel, thanks to you for taking the time to review it and explained me the best approach to implement what I wanted to add.

**Pull request merged**
